### ISSUE TITLE
Multithreading JkLog initialization issue

### ISSUE THREAD

**Issue by promne** [jerkar/jeka#136]
The static block sets the START_TIME value only for the thread this class was loaded from

https://github.com/jerkar/jeka/blob/dccd5967d827072c0d36b9183850ef362cf660bc/dev.jeka.core/src/main/java/dev/jeka/core/api/system/JkLog.java#L48-L52

Causing NPE down the line in another thread:
`
Caused by: java.lang.NullPointerException
	at dev.jeka.core.api.system.JkLog.startTask(JkLog.java:139)
	at dev.jeka.core.api.depmanagement.JkDependencyResolver.resolve(JkDependencyResolver.java:86)
`

**Comment by djeang** [comment]
In fact, Jeka logging was not design with multithreadingin in mind. The reason is that multiple threads logging concurrently into a single target (typically a console) wouldl lead in a confusing output.

As a quick win, Jeka could ignore logs issued by other threads than the one that initialized JkLog.

Would it helps you  ? Have you got extra suggestions ?

**Comment by djeang** [comment]
For now, I will just fix the NPE, letting the output of each thread to mix each other. 
You're welcome to request improvements about the readability of the output.

**Comment by promne** [comment]
Yeah, it looks like the threading wasn't part of the design, the use of ThreadLocal is confusing in that way.

I don't know an easy fix for this, without knowing the rest of the framework. I would suggest probably to change the type of START_TIMES to be a ConcurrentLinkedList?

Or to keep what you have done and make it "nicer" using https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html#withInitial-java.util.function.Supplier-
